name: deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependency
        run: yarn install

      - name: Run test
        run: yarn run test

  deploy-QAS:
    runs-on: ubuntu-latest
    environment:
      name: QAS
    needs: tests
    steps:
      - name: Deploy Project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Deploy to qas-pages
        uses: peaceiris/actions-qas-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  deploy-PROD:
    runs-on: ubuntu-latest
    environment:
      name: PROD
    needs: deploy-QAS
    steps:
      - name: Deploy Project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Deploy to prod-pages
        uses: peaceiris/actions-prod-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build