name: deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependency
        run: yarn install

      - name: Run test
        run: yarn test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-QAS:
    runs-on: ubuntu-latest
    environment:
      name: QAS
    needs: tests
    steps:
      - name: Deploy Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'QAS-Pages'

  deploy-PROD:
    runs-on: ubuntu-latest
    environment:
      name: PROD
    needs: deploy-QAS
    steps:
      - name: Deploy Project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build web-app
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build