name: tests

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependency
        run: yarn install

      - name: Run test
        run: yarn run test
